#!/bin/sh
set -e

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew install openjdk@21

: "${SUPABASE_URL:?SUPABASE_URL env var not set}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY env var not set}"

cat > "$CI_PRIMARY_REPOSITORY_PATH/config.properties" <<EOF
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SENTRY_DSN_ANDROID=${SENTRY_DSN_ANDROID:-}
EOF
